server:
  port: 8089

spring:
  datasource:
    url: jdbc:mysql://129.204.69.51:3306/service_platform
    username: root
    password: hY434513
    driver-class-name: com.mysql.jdbc.Driver
  # SpringMVC视图解析器配置
  mvc:
    view:
      prefix: /META-INF/resources/
      suffix: .jsp

#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.school.design.automobile_sales_mall.entity

mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.school.design.automobile_sales_mall.entity


logging:
  level:
    com:
      school:
        design:
          automobile_sales_mall:
            mapper: debug
